### PR TITLE
Added a GitHub action that deploys to Github Pages

### PR DESCRIPTION
**Pull request by ColinEberhardt**
Runs the build then deploys the entire repo contents to gh-pages. This is a bit messy, but works for now.

Here's the app: https://colineberhardt.github.io/FDC3-conformance-framework-1/app/

And an example mock: https://colineberhardt.github.io/FDC3-conformance-framework-1/mock/general/

### CODE REVIEW

**Review by robmoffat — APPROVED** [review]
good work!

**Comment by ColinEberhardt** [comment]
@robmoffat I've just updated the required configuration and will re-build. This should fix the GH Action error:

image

**Comment by robmoffat** [comment]
Seems like it's working: https://finos.github.io/FDC3-conformance-framework/app/

**Comment by ColinEberhardt** [comment]
@robmoffat => https://github.com/finos/FDC3-conformance-framework/tree/main/mock#mock-app-configuration

**Pull request merged**
