### PR TITLE
Mao's Security Scanning

### PR DESCRIPTION
**Pull request by robmoffat**
Adding security scanning tests for a JS project.

### CODE REVIEW

**Comment by robmoffat** [comment]
are we not doing this then?

**Comment by robmoffat** [comment]
re-opening.

**Comment by robmoffat** [comment]
@ColinEberhardt these GitHub actions are correctly passing on my up-to-date fork: https://github.com/robmoffat/FDC3-conformance-framework/actions

Can we merge this please?

**Review by ColinEberhardt — APPROVED** [review]

**Comment by ColinEberhardt** [comment]
> Can we merge this please?

Sorry, no idea why I closed this previously! Must have got lost in the sea of notifications.

**Pull request merged**
